[tool.poetry]
name = "django-course-work"
version = "0.1.0"
description = ""
authors = ["Ivan_K <ikalinov1989yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.2.4"
dotenv = "^0.9.9"
psycopg2 = "^2.9.10"
black = "^25.1.0"
isort = "^6.0.1"
flake8 = "^7.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
